/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Shalva
 */
public class viewAdminstrador extends javax.swing.JFrame {

    /**
     * Creates new form viewAdminstrador
     */
    public viewAdminstrador() {
        initComponents();
    }

    public JMenu getjMenu() {
        return jMenu;
    }

    public void setjMenu(JMenu jMenu) {
        this.jMenu = jMenu;
    }

    public JMenuItem getjMenuPersonas() {
        return jMenuPersonas;
    }

    public void setjMenuPersonas(JMenuItem jMenuPersonas) {
        this.jMenuPersonas = jMenuPersonas;
    }

    public JMenuItem getjMenuProducto() {
        return jMenuProducto;
    }

    public void setjMenuProducto(JMenuItem jMenuProducto) {
        this.jMenuProducto = jMenuProducto;
    }

    public JMenuItem getjMenuUsuario() {
        return jMenuUsuario;
    }

    public void setjMenuUsuario(JMenuItem jMenuUsuario) {
        this.jMenuUsuario = jMenuUsuario;
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuPersonas = new javax.swing.JMenuItem();
        jMenuProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuEditarPersonas = new javax.swing.JMenuItem();
        jMenuVisualPersonas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jMenu.setText("Configuracion");

        jMenuUsuario.setText("Usuario");
        jMenu.add(jMenuUsuario);

        jMenuPersonas.setText("Personas");
        jMenu.add(jMenuPersonas);

        jMenuProducto.setText("Producto");
        jMenu.add(jMenuProducto);

        jMenuBar1.add(jMenu);

        jMenu2.setText("Reporte");

        jMenuEditarPersonas.setText("Editar Personas");
        jMenu2.add(jMenuEditarPersonas);

        jMenuVisualPersonas.setText("Visualizar Personas");
        jMenu2.add(jMenuVisualPersonas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEditarPersonas;
    private javax.swing.JMenuItem jMenuPersonas;
    private javax.swing.JMenuItem jMenuProducto;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JMenuItem jMenuVisualPersonas;
    // End of variables declaration//GEN-END:variables
}
